service: my-lambda-function
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs12.x
  region: us-east-1

functions:
  hello:
    handler: handler.lambdaFunction
    events:
      - http:
          path: /hello
          method: get
